runtime: nodejs18 # or another supported version

instance_class: F2

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  PORT: 80
  MODE: production
  NODE_ENV: production