runtime: nodejs18 # or another supported version

instance_class: F2

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

ports:
  - name: https # Use http or https
      protocol: TCP
      port: 8080
      targetPort: 8080